# Generated by Django 5.1.2 on 2024-10-24 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kindergarten', '0013_alter_photoprice_region'),
        ('roles', '0007_remove_employee_department_remove_employee_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children_count', models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во детей')),
                ('last_photographer', models.CharField(max_length=256, null=True, verbose_name='Последний фотограф')),
                ('garden_details', models.CharField(max_length=256, null=True, verbose_name='Реквизиты')),
                ('city', models.CharField(max_length=128, null=True, verbose_name='Город')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Звонки'), (2, 'Идет фотосессия'), (3, 'Печать фото'), (4, 'Продажа фото')], default=1, verbose_name='Статус карточки клиента')),
                ('kindergarten', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kindergarten.kindergarten', verbose_name='Сад')),
                ('responsible_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_cards', to='roles.employee', verbose_name='Ответственный менеджер')),
            ],
            options={
                'verbose_name': 'Карточка клиента',
                'verbose_name_plural': 'Карточки клиента',
            },
        ),
        migrations.CreateModel(
            name='ClientCardTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1024, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('task_status', models.PositiveSmallIntegerField(choices=[(1, 'Открыта'), (2, 'В работе'), (3, 'Готово')], default=1, verbose_name='Статус задачи')),
                ('task_type', models.PositiveSmallIntegerField(choices=[(1, 'Звонок')], default=1, verbose_name='Тип задачи')),
                ('date_end', models.DateTimeField(verbose_name='Дата окончания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_card_tasks', to='roles.employee', verbose_name='Автор заметки')),
                ('client_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_card_task', to='client_cards.clientcard', verbose_name='Карточка клиента')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='HistoryCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_status', models.PositiveSmallIntegerField(choices=[(1, 'Отказ'), (2, 'Записан на фотосессию'), (3, 'Отправлено КП')], default=3, verbose_name='Статус звонка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_calls', to='roles.employee', verbose_name='Автор заметки')),
                ('client_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_calls', to='client_cards.clientcard', verbose_name='Карточка клиента')),
            ],
            options={
                'verbose_name': 'История звонка',
                'verbose_name_plural': 'История звонков',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1024, verbose_name='Текст заметки')),
                ('priority', models.BooleanField(default=False, verbose_name='Приоритет заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='roles.employee', verbose_name='Автор заметки')),
                ('client_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='client_cards.clientcard', verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
            },
        ),
    ]
