# Generated by Django 5.1.2 on 2024-10-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcard',
            name='address',
            field=models.CharField(max_length=256, null=True, verbose_name='Адрес'),
        ),
    ]
