# Generated by Django 5.1.2 on 2024-10-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_cards', '0002_clientcard_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcard',
            name='charge_dates',
            field=models.DateField(null=True, verbose_name='Дата сбора'),
        ),
        migrations.AddField(
            model_name='clientcard',
            name='charges',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Сбор'),
        ),
    ]
