# Generated by Django 5.1.2 on 2024-10-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_cards', '0003_clientcard_charge_dates_clientcard_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcard',
            name='children_for_photoshoot',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во детей на фотосессию'),
        ),
    ]
