# Generated by Django 5.1.2 on 2024-10-30 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_cards', '0004_clientcard_children_for_photoshoot'),
        ('roles', '0007_remove_employee_department_remove_employee_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcardtask',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_card_tasks', to='roles.employee', verbose_name='Автор задачи'),
        ),
        migrations.AlterField(
            model_name='historycall',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_calls', to='roles.employee', verbose_name='Автор звонка'),
        ),
    ]
