# Generated by Django 5.1.2 on 2024-11-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_cards', '0005_alter_clientcardtask_author_alter_historycall_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcard',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменен'),
        ),
    ]
