# Generated by Django 5.1.3 on 2024-11-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_cards', '0006_clientcard_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historycall',
            name='created_at',
            field=models.DateTimeField(verbose_name='Время создания'),
        ),
    ]
