# Generated by Django 5.1.3 on 2024-11-07 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_cards', '0007_alter_historycall_created_at'),
        ('roles', '0008_alter_employee_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcardtask',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executed_client_card_tasks', to='roles.employee', verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='clientcardtask',
            name='revision_comment',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='clientcardtask',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_client_card_tasks', to='roles.employee', verbose_name='Автор задачи'),
        ),
        migrations.AlterField(
            model_name='clientcardtask',
            name='client_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_card_task', to='client_cards.clientcard', verbose_name='Карточка клиента'),
        ),
        migrations.AlterField(
            model_name='clientcardtask',
            name='task_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Открыта'), (2, 'Выполнена')], default=1, verbose_name='Статус задачи'),
        ),
        migrations.AlterField(
            model_name='clientcardtask',
            name='task_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Звонок'), (2, 'Сбор оплаты+ отправка ссылок'), (3, 'Принять заказ'), (4, 'Позвонить холодный/списки'), (5, 'Проверить отправку образцов, Готовые фото.'), (6, 'Теплые сады'), (7, 'Напомнить о записи'), (8, 'Позвонить по КП, Проверить смс по Вотсапп')], default=1, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='clientcardtask',
            name='text',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Описание'),
        ),
    ]
