# Generated by Django 5.0.6 on 2024-07-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0004_alter_promocodephototypes_options_bonuscoupon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonuscoupon',
            options={'verbose_name': 'Бонусный купон', 'verbose_name_plural': 'Бонусные купоны'},
        ),
    ]
