# Generated by Django 5.0.6 on 2024-07-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0006_bonuscoupon_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocodephototypes',
            name='photo_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '10x15'), (2, '15x20'), (3, '20x30'), (4, 'Магнит'), (5, 'Календарь'), (6, 'Фотокнига'), (0, 'Электронные фото')], verbose_name='Тип фото, к которой применяется скидка'),
        ),
    ]
