# Generated by Django 5.0.8 on 2024-08-20 21:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0010_alter_phototheme_options'),
        ('promocode', '0007_alter_promocodephototypes_photo_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ('-created',), 'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
        migrations.AddField(
            model_name='promocode',
            name='discount_photobooks',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Скидка на фотокниги (%)'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='discount_services',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Скидка на все услуги (%)'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='photo_theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='photo.phototheme', verbose_name='Фототема'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocode',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to=settings.AUTH_USER_MODEL, verbose_name='Заведующий'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=200, unique=True, verbose_name='Промокод'),
        ),
        migrations.DeleteModel(
            name='PromocodePhotoTypes',
        ),
    ]
