# Generated by Django 5.0.8 on 2024-08-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0008_alter_promocode_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuscoupon',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Баланс купона'),
        ),
    ]
