# Generated by Django 5.1.2 on 2024-10-29 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0017_alter_phototheme_options_phototheme_season_and_more'),
        ('promocode', '0009_alter_bonuscoupon_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='photo_theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='photo.phototheme', verbose_name='Фотосессия'),
        ),
    ]
