# Generated by Django 5.1.2 on 2024-10-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0010_alter_promocode_photo_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='activate_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во активаций промо кода'),
        ),
    ]
