# Generated by Django 5.1.3 on 2024-11-19 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0027_remove_kindergartenphototheme_unique_active_photo_theme_per_kindergarten_and_more'),
        ('promocode', '0011_promocode_activate_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='photo_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='photo.phototheme', verbose_name='Фотосессия'),
        ),
    ]
