version: '3.8'

x-function: &base_web
  working_dir: /opt/backend
  depends_on:
    - db
    - redis
  networks:
    - nginx_network
  env_file:
    - .env

services:

  nginx:
    build: ./nginx/prod
    container_name: ${PROJECT_SLUG}_nginx
    volumes:
      - static_dir:/opt/backend/static/
      - media_dir:/opt/backend/media/
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Монтируем сертификаты
      - ./certbot/www:/var/www/certbot
    ports:
      - "8080:8080"
      - "443:443"
    depends_on:
      - web
      - frontend
    networks:
      - nginx_network

  web:
    <<: *base_web
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    container_name: ${PROJECT_SLUG}_app
    volumes:
      - static_dir:/opt/backend/static/
      - media_dir:/opt/backend/media/
      - ./backend:/opt/backend:rw
    ports:
      - "8000:8000"

  celery-worker:
    <<: *base_web
    build:
      context: ./backend
      dockerfile: celery.dockerfile
    container_name: ${PROJECT_SLUG}_celery_worker
    volumes:
      - ./backend/:/opt/backend/:rw
      - static_dir:/opt/backend/static/
      - media_dir:/opt/backend/media/
    command: >
      sh -c "
      python manage.py migrate --no-input &&
      celery -A config.celery worker --loglevel=info --max-tasks-per-child=300 -P prefork
      "
    restart: always

  celery-beat:
    <<: *base_web
    build:
      context: ./backend
      dockerfile: celery.dockerfile
    container_name: ${PROJECT_SLUG}_celery_beat
    volumes:
      - ./backend/:/opt/backend/:rw
      - static_dir:/opt/backend/static/
      - media_dir:/opt/backend/media/
    command: >
      sh -c "
      python manage.py migrate --no-input &&
      celery -A config.celery beat -S django --loglevel=info
      "
    restart: always

  celery-flower:
    <<: *base_web
    build:
      context: ./backend
      dockerfile: celery.dockerfile
    container_name: ${PROJECT_SLUG}_celery_flower
    volumes:
      - ./backend/:/opt/backend/:rw
      - static_dir:/opt/backend/static/
      - media_dir:/opt/backend/media/
    command: >
      sh -c "
      python manage.py migrate --no-input &&
      celery -A config.celery flower --loglevel=info --port=5555 --basic_auth=${FLOWER_USER}:${FLOWER_PASSWORD}
      "
    ports:
      - "5555:5555"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: prod.frontend.dockerfile
    container_name: ${PROJECT_SLUG}_frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      nginx_network:

  db:
    image: postgres:16
    container_name: ${PROJECT_SLUG}_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - nginx_network

  redis:
    image: redis:latest
    container_name: ${PROJECT_SLUG}_redis
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - nginx_network

volumes:
  static_dir:
  media_dir:
  pgdata:
  redis_data:

networks:
  nginx_network:
