# Generated by Django 5.0.6 on 2024-07-03 15:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phototheme',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phototheme',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменен'),
        ),
    ]
