# Generated by Django 5.0.6 on 2024-07-08 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0001_initial'),
        ('photo', '0002_phototheme_created_phototheme_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='child.child', verbose_name='Ребенок'),
        ),
    ]
