# Generated by Django 5.0.7 on 2024-07-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_photoline_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='serial_number',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Фото 1'), (2, 'Фото 2'), (3, 'Фото 3'), (4, 'Фото 4'), (5, 'Фото 5'), (6, 'Фото 6')], default=1, verbose_name='Порядковый номер'),
            preserve_default=False,
        ),
    ]
