# Generated by Django 5.0.7 on 2024-07-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_alter_photoline_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.PositiveSmallIntegerField(choices=[(1, '10x15'), (2, '15x20'), (3, '20x30'), (4, 'Магнит'), (5, 'Календарь'), (6, 'Фотокнига'), (0, 'Электронные фото')], verbose_name='Тип фотографии')),
                ('coefficient', models.FloatField(verbose_name='Коэффициент')),
            ],
            options={
                'verbose_name': 'Коэффициент популярности фотографий',
                'verbose_name_plural': 'Коэффициенты популярности фотографий',
            },
        ),
        migrations.CreateModel(
            name='PhotoPopularityStat',
            fields=[
            ],
            options={
                'verbose_name': 'Статистика популярности фотографий',
                'verbose_name_plural': 'Статистики популярности фотографий',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('photo.phototheme',),
        ),
        migrations.AddField(
            model_name='photo',
            name='serial_number',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Фото 1'), (2, 'Фото 2'), (3, 'Фото 3'), (4, 'Фото 4'), (5, 'Фото 5'), (6, 'Фото 6')], default=1, verbose_name='Порядковый номер'),
            preserve_default=False,
        ),
    ]
