# Generated by Django 5.0.7 on 2024-07-28 12:18

from django.db import migrations

from apps.kindergarten.models import PhotoType


def insert_coefficient(apps, schema_editor):
    Coefficient = apps.get_model("photo", "Coefficient")
    objects = [
        Coefficient(photo_type=PhotoType.size_10x15, coefficient=1),
        Coefficient(photo_type=PhotoType.size_15x20, coefficient=1.5),
        Coefficient(photo_type=PhotoType.size_20x30, coefficient=2),
        Coefficient(photo_type=PhotoType.magnet, coefficient=1.7),
        Coefficient(photo_type=PhotoType.calendar, coefficient=3.5),
        Coefficient(photo_type=PhotoType.photobook, coefficient=10),
    ]
    Coefficient.objects.bulk_create(objects)


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_coefficient_photopopularitystat_photo_serial_number'),
    ]

    operations = [
        migrations.RunPython(insert_coefficient),
    ]
