# Generated by Django 5.0.8 on 2024-08-20 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0008_phototheme_are_qrs_removed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photoline',
            options={'verbose_name': 'Пробник', 'verbose_name_plural': 'Пробники'},
        ),
        migrations.AlterModelOptions(
            name='phototheme',
            options={'ordering': ('-created',), 'verbose_name': 'Тема фотосессии', 'verbose_name_plural': 'Темы фотосессий'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='photo.photoline', verbose_name='Пробник'),
        ),
    ]
