# Generated by Django 5.1.1 on 2024-09-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0012_phototheme_ransom_counted'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='watermarked_photo',
            field=models.ImageField(blank=True, null=True, upload_to='watermarked_photo/', verbose_name='Фотография с водяным знаком'),
        ),
    ]
