# Generated by Django 5.1.1 on 2024-10-01 07:51

import apps.photo.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0013_photo_watermarked_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoline',
            name='qr_code',
            field=apps.photo.fields.NullImageField(blank=True, null=True, unique=True, upload_to='photo_line/', verbose_name='QR код'),
        ),
    ]
