# Generated by Django 5.1.2 on 2024-10-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0014_alter_photoline_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_file',
            field=models.FileField(default='', upload_to='', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь к фотографии'),
        ),
    ]
