# Generated by Django 5.1.2 on 2024-10-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0015_remove_photo_photo_photo_photo_file_photo_photo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='watermarked_photo_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь к фотографии с water маркой'),
        ),
    ]
