# Generated by Django 5.1.2 on 2024-10-29 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0016_photo_watermarked_photo_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phototheme',
            options={'ordering': ('-created',), 'verbose_name': 'Фотосессия', 'verbose_name_plural': 'Фотосессии'},
        ),
        migrations.AddField(
            model_name='phototheme',
            name='season',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Winter'), (2, 'Spring'), (3, 'Summer'), (4, 'Autumn')], default=1, verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='number',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='photoline',
            name='photo_theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photo_lines', to='photo.phototheme', verbose_name='Фотосессия'),
        ),
        migrations.AlterField(
            model_name='userphotocount',
            name='photo_theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.phototheme', verbose_name='фотосесиия'),
        ),
    ]
