# Generated by Django 5.1.2 on 2024-10-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0017_alter_phototheme_options_phototheme_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phototheme',
            name='season',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Зима'), (2, 'Весна'), (3, 'Лето'), (4, 'Осень')], default=1, verbose_name='Сезон'),
        ),
    ]
