# Generated by Django 5.1.2 on 2024-11-01 08:58

import apps.photo.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0018_alter_phototheme_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoline',
            name='qr_code',
            field=apps.photo.fields.NullImageField(blank=True, null=True, upload_to='photo_line/', verbose_name='QR код'),
        ),
    ]
