# Generated by Django 5.1.2 on 2024-11-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0019_alter_photoline_qr_code'),
        ('photo', '0019_phototheme_kindergarten'),
    ]

    operations = [
    ]
