# Generated by Django 5.1.2 on 2024-11-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0020_merge_20241103_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Фотография'),
        ),
    ]
