# Generated by Django 5.1.2 on 2024-11-06 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0022_remove_phototheme_kindergarten_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userphotocount',
            options={'verbose_name': 'Счетчик пробников у пользователя', 'verbose_name_plural': 'Счетчик пробников у пользователя'},
        ),
        migrations.AlterField(
            model_name='userphotocount',
            name='count',
            field=models.PositiveIntegerField(default=3, verbose_name='Осталось пробников добавить'),
        ),
        migrations.AlterField(
            model_name='userphotocount',
            name='photo_theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.phototheme', verbose_name='Фотосессия'),
        ),
        migrations.AlterField(
            model_name='userphotocount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
