# Generated by Django 5.1.3 on 2024-11-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0023_alter_userphotocount_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveSmallIntegerField(choices=[(1, 'Зима'), (2, 'Весна'), (3, 'Лето'), (4, 'Осень')], default=1, verbose_name='Сезон')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
            },
        ),
        migrations.AlterField(
            model_name='phototheme',
            name='season',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Зима'), (2, 'Весна'), (3, 'Лето'), (4, 'Осень')], default=1, null=True, verbose_name='Сезон'),
        ),
    ]
