# Generated by Django 5.1.3 on 2024-11-12 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0024_season_alter_phototheme_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phototheme',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photo_themes', to='photo.season', verbose_name='Сезон'),
        ),
    ]
