# Generated by Django 5.1.3 on 2024-11-14 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0014_alter_photoprice_region'),
        ('photo', '0026_remove_phototheme_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='kindergartenphototheme',
            name='unique_active_photo_theme_per_kindergarten',
        ),
        migrations.AlterField(
            model_name='kindergartenphototheme',
            name='photo_theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kindergartenphototheme', to='photo.phototheme', verbose_name='Фотосессия'),
        ),
        migrations.AddConstraint(
            model_name='kindergartenphototheme',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('kindergarten',), name='unique_active_photo_theme_per_kindergarten', violation_error_message='У детского сада не может быть более одной активной фототемы.'),
        ),
    ]
