# Generated by Django 5.1.3 on 2024-11-23 15:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0028_alter_season_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phototheme',
            name='date_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала'),
        ),
    ]
