# Generated by Django 5.1.3 on 2024-11-23 15:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0029_alter_phototheme_date_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoThemeName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=255, verbose_name='Тема фотосессии')),
            ],
            options={
                'verbose_name': 'Тема фотосессии',
                'verbose_name_plural': 'Темы фотосессии',
            },
        ),
        migrations.AlterField(
            model_name='phototheme',
            name='date_start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='phototheme',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='phototheme',
            name='photo_theme_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photo.photothemename', verbose_name='Тема фотосессии'),
        ),
    ]
