# Generated by Django 5.1.3 on 2024-11-23 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0030_photothemename_alter_phototheme_date_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phototheme',
            name='date_end',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата окончания'),
        ),
    ]
