# Generated by Django 5.1.3 on 2024-12-02 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0031_alter_phototheme_date_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phototheme',
            name='season',
        ),
        migrations.AddField(
            model_name='photothemename',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photo_themes', to='photo.season', verbose_name='Сезон'),
        ),
    ]
