# Generated by Django 5.1.6 on 2025-02-11 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0033_kindergartenphototheme_ya_disk_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phototheme',
            options={'ordering': ('-created',), 'verbose_name': 'Фотосессия', 'verbose_name_plural': ' Фотосессии'},
        ),
    ]
