# Generated by Django 5.1.7 on 2025-03-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0034_alter_phototheme_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoline',
            name='child_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядок ребенка'),
        ),
    ]
