# Generated by Django 5.1.7 on 2025-04-08 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0035_photoline_child_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoline',
            name='parent',
        ),
        migrations.AddField(
            model_name='photoline',
            name='parent',
            field=models.ManyToManyField(blank=True, null=True, related_name='photo_lines', to=settings.AUTH_USER_MODEL, verbose_name='Родитель'),
        ),
    ]
