# Generated by Django 5.1.7 on 2025-04-10 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0036_remove_photoline_parent_photoline_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentPhotoLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_number', models.IntegerField(verbose_name='Порядковый номер ребенка')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_photo_lines', to=settings.AUTH_USER_MODEL)),
                ('photo_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_photo_lines', to='photo.photoline')),
            ],
            options={
                'unique_together': {('parent', 'photo_line')},
            },
        ),
    ]
