# Generated by Django 5.1.7 on 2025-04-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0037_parentphotoline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentphotoline',
            name='child_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядковый номер ребенка'),
        ),
    ]
