# Generated by Django 5.0.7 on 2024-07-26 02:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photo', '0004_alter_photoline_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('is_active', models.BooleanField(default=True, verbose_name='Корзина активна')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='CartPhotoLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_digital', models.BooleanField(default=False, verbose_name='Электронные фотографии')),
                ('is_photobook', models.BooleanField(default=False, verbose_name='Фотокнига')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая стоимость')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_photo_lines', to='cart.cart', verbose_name='Корзина')),
                ('photo_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_photo_lines', to='photo.photoline', verbose_name='Фотолиния')),
            ],
            options={
                'verbose_name': 'Фотолиния в корзине',
                'verbose_name_plural': 'Фотолинии в корзине',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='photo_lines',
            field=models.ManyToManyField(through='cart.CartPhotoLine', to='photo.photoline', verbose_name='Фотолинии'),
        ),
        migrations.CreateModel(
            name='PhotoInCart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_type', models.PositiveSmallIntegerField(choices=[(1, '10x15'), (2, '15x20'), (3, '20x30'), (4, 'Магнит'), (5, 'Календарь'), (6, 'Фотокнига'), (0, 'Электронные фото')], verbose_name='Тип фото')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('price_per_piece', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость за шт.')),
                ('discount_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость со скидкой')),
                ('cart_photo_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_in_cart', to='cart.cartphotoline', verbose_name='Фотолиния')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_in_cart', to='photo.photo', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото в корзине',
            },
        ),
        migrations.AddField(
            model_name='cartphotoline',
            name='photos',
            field=models.ManyToManyField(through='cart.PhotoInCart', to='photo.photo', verbose_name='Фото'),
        ),
    ]
