# Generated by Django 5.0.7 on 2024-07-26 05:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photoincart',
            options={'verbose_name': 'Фото в корзине', 'verbose_name_plural': 'Фото в корзине'},
        ),
        migrations.CreateModel(
            name='CartPhotoLinePhotoInCart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cart_photo_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_photo_line_photo_in_cart', to='cart.cartphotoline', verbose_name='Фотолиния в корзине')),
                ('photo_in_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_photo_line_photo_in_cart', to='cart.photoincart', verbose_name='Фото в корзине')),
            ],
            options={
                'verbose_name': 'Доп таблица для связи PhotoInCart и CartPhotoLine',
                'verbose_name_plural': 'Доп таблица для связи PhotoInCart и CartPhotoLine',
            },
        ),
        migrations.AlterField(
            model_name='cartphotoline',
            name='photos',
            field=models.ManyToManyField(through='cart.CartPhotoLinePhotoInCart', to='cart.photoincart', verbose_name='Фото'),
        ),
    ]
