# Generated by Django 5.0.8 on 2024-08-20 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cartphotoline_photos_and_more'),
        ('photo', '0009_alter_photoline_options_alter_phototheme_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartphotoline',
            options={'verbose_name': 'Пробник в корзине', 'verbose_name_plural': 'Пробники в корзине'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='photo_lines',
            field=models.ManyToManyField(through='cart.CartPhotoLine', to='photo.photoline', verbose_name='Пробники'),
        ),
        migrations.AlterField(
            model_name='cartphotoline',
            name='photo_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_photo_lines', to='photo.photoline', verbose_name='Пробник'),
        ),
        migrations.AlterField(
            model_name='photoincart',
            name='cart_photo_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_in_cart', to='cart.cartphotoline', verbose_name='Пробник'),
        ),
    ]
