# Generated by Django 5.0.8 on 2024-08-23 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartphotoline_options_alter_cart_photo_lines_and_more'),
        ('promocode', '0008_alter_promocode_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='promocode.promocode', verbose_name='Промокод'),
        ),
    ]
