# Generated by Django 5.0.8 on 2024-08-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='bonus_coupon',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Баланс купона'),
        ),
        migrations.AddField(
            model_name='cart',
            name='order_fully_paid_by_coupon',
            field=models.BooleanField(default=False, verbose_name='Заказ полностью оплачен купоном'),
        ),
    ]
