# Generated by Django 5.1.1 on 2024-09-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cart_bonus_coupon_cart_order_fully_paid_by_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartphotoline',
            name='is_free_calendar',
            field=models.BooleanField(default=False, verbose_name='Бесплатный календарь'),
        ),
    ]
