# Generated by Django 5.1.4 on 2024-12-15 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_cartphotoline_is_free_digital'),
        ('photo', '0032_remove_phototheme_season_photothemename_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoincart',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos_in_cart', to='photo.photo', verbose_name='Фото'),
        ),
    ]
