# Generated by Django 5.1.5 on 2025-02-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_cartphotoline_options_cartphotoline_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartphotoline',
            options={'ordering': ('created_at',), 'verbose_name': 'Пробник в корзине', 'verbose_name_plural': 'Пробники в корзине'},
        ),
        migrations.AddField(
            model_name='cartphotoline',
            name='child_number',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Номер ребенка'),
        ),
    ]
