# Generated by Django 5.1.6 on 2025-02-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_alter_cartphotoline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartphotoline',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Изначальная сумма заказа'),
        ),
    ]
