# Generated by Django 5.1.6 on 2025-03-02 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_cartphotoline_original_price'),
        ('photo', '0034_alter_phototheme_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartphotoline',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_photo_lines', to='cart.cart', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='cartphotoline',
            name='photo_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_photo_lines', to='photo.photoline', verbose_name='Пробник'),
        ),
    ]
