# Generated by Django 5.1.6 on 2025-03-05 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_alter_cartphotoline_cart_and_more'),
        ('kindergarten', '0019_remove_kindergarten_orig_folder_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartphotoline',
            name='kindergarten',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kindergarten_cart_photo_lines', to='kindergarten.kindergarten', verbose_name='Детский сад'),
        ),
        migrations.AddField(
            model_name='cartphotoline',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_cart_photo_lines', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
