# Generated by Django 5.1.7 on 2025-03-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_cartphotoline_kindergarten_cartphotoline_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartphotoline',
            name='digital_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена за эл. фото'),
        ),
        migrations.AddField(
            model_name='cartphotoline',
            name='photo_book_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена за фото книгу'),
        ),
    ]
