# Generated by Django 5.1.7 on 2025-03-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_cartphotoline_digital_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartphotoline',
            name='all_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена с пересчетом id_digital'),
        ),
    ]
