# Generated by Django 5.1.7 on 2025-03-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_cartphotoline_all_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartphotoline',
            name='all_price',
            field=models.IntegerField(default=0, verbose_name='Цена с пересчетом id_digital'),
        ),
        migrations.AlterField(
            model_name='cartphotoline',
            name='digital_price',
            field=models.IntegerField(default=0, verbose_name='Цена за эл. фото'),
        ),
        migrations.AlterField(
            model_name='cartphotoline',
            name='photo_book_price',
            field=models.IntegerField(default=0, verbose_name='Цена за фото книгу'),
        ),
    ]
