# Generated by Django 5.1.7 on 2025-04-08 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_alter_cartphotoline_all_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartphotoline',
            name='user',
        ),
        migrations.AddField(
            model_name='cartphotoline',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_cart_photo_lines', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
