# Generated by Django 5.0.6 on 2024-06-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoprice',
            name='photo_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '10x15'), (2, '15x20'), (3, '20x30'), (4, 'Магнит'), (5, 'Календарь'), (6, 'Фотокнига')], default=1, verbose_name='Тип фотографии'),
        ),
    ]
