# Generated by Django 5.0.6 on 2024-07-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0003_alter_photoprice_photo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='country',
            field=models.CharField(default='Россия', max_length=255, verbose_name='Страна'),
        ),
    ]
