# Generated by Django 5.0.7 on 2024-07-26 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0005_alter_region_options'),
        ('photo', '0005_coefficient_photopopularitystat_photo_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ransom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ransom_amount', models.PositiveSmallIntegerField(default=0, verbose_name='Сумма выкупа')),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ransoms', to='kindergarten.kindergarten', verbose_name='Детский сад')),
                ('photo_theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ransoms', to='photo.phototheme', verbose_name='Тема фотосессии')),
            ],
            options={
                'verbose_name': 'Сумма выкупа',
                'verbose_name_plural': 'Суммы выкупов',
            },
        ),
    ]
