# Generated by Django 5.0.7 on 2024-08-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0006_ransom'),
    ]

    operations = [
        migrations.AddField(
            model_name='kindergarten',
            name='locality',
            field=models.CharField(default=1, max_length=255, verbose_name='Населенный пункт'),
            preserve_default=False,
        ),
    ]
