# Generated by Django 5.0.7 on 2024-08-05 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0007_alter_kindergarten_name_alter_region_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindergarten',
            name='name',
            field=models.CharField(max_length=56, validators=[django.core.validators.RegexValidator(message='Можно вводить только кириллические символы, пробелы, тире и кавычки.', regex='^[А-Яа-яЁё\\s/\\\'"-]+$'), django.core.validators.MinLengthValidator(2)], verbose_name='Название'),
        ),
    ]
