# Generated by Django 5.0.7 on 2024-07-28 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0007_kindergarten_locality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindergarten',
            name='name',
            field=models.CharField(max_length=56, validators=[django.core.validators.RegexValidator(message='Можно вводить только кириллические символы, пробелы, тире и кавычки.', regex='^[А-Яа-яЁё\\s-\\\'"]+$'), django.core.validators.MinLengthValidator(2)], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.CharField(default='Россия', max_length=56, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=56, unique=True, validators=[django.core.validators.RegexValidator(message='Можно вводить только кириллические символы, пробелы и тире.', regex='^[А-Яа-яЁё\\s-]+$'), django.core.validators.MinLengthValidator(2)], verbose_name='Название региона'),
        ),
    ]
