# Generated by Django 5.1.1 on 2024-09-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0010_alter_kindergarten_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='ransom_amount',
        ),
        migrations.AddField(
            model_name='region',
            name='ransom_amount_for_calendar',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Сумма выкупа для календаря'),
        ),
        migrations.AddField(
            model_name='region',
            name='ransom_amount_for_digital_photos',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Сумма выкупа для электронных фотографий'),
        ),
    ]
