# Generated by Django 5.1.1 on 2024-10-08 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0012_alter_photoprice_photo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoprice',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photo_prices', to='kindergarten.region', verbose_name='Регион'),
        ),
    ]
