# Generated by Django 5.1.3 on 2024-11-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0014_alter_photoprice_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='ransom',
            name='average_bill',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Средний чек'),
        ),
    ]
