# Generated by Django 5.1.5 on 2025-02-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0015_ransom_average_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='ransom_amount_for_calendar_second',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Сумма выкупа для календаря второго ребенка'),
        ),
        migrations.AddField(
            model_name='region',
            name='ransom_amount_for_calendar_third',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Сумма выкупа для календаря третьего ребенка'),
        ),
        migrations.AddField(
            model_name='region',
            name='ransom_amount_for_digital_photos_second',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Сумма выкупа для электронных фотографий второго ребенка'),
        ),
        migrations.AddField(
            model_name='region',
            name='ransom_amount_for_digital_photos_third',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Сумма выкупа для электронных фотографий третьего ребенка'),
        ),
    ]
