# Generated by Django 5.1.6 on 2025-02-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0016_region_ransom_amount_for_calendar_second_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kindergarten',
            name='original_photos_folder_url',
            field=models.URLField(blank=True, null=True, verbose_name='Папка с оригиналами фото'),
        ),
        migrations.AddField(
            model_name='kindergarten',
            name='watermarked_photos_folder_url',
            field=models.URLField(blank=True, null=True, verbose_name='Папка с фото с вотермарками'),
        ),
    ]
