# Generated by Django 5.1.6 on 2025-02-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0017_kindergarten_original_photos_folder_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kindergarten',
            old_name='original_photos_folder_url',
            new_name='orig_folder_url',
        ),
        migrations.RenameField(
            model_name='kindergarten',
            old_name='watermarked_photos_folder_url',
            new_name='watermarked_folder_url',
        ),
    ]
