# Generated by Django 5.1.6 on 2025-02-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0018_rename_original_photos_folder_url_kindergarten_orig_folder_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kindergarten',
            name='orig_folder_url',
        ),
        migrations.RemoveField(
            model_name='kindergarten',
            name='watermarked_folder_url',
        ),
    ]
