# Generated by Django 5.1.7 on 2025-03-19 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0019_remove_kindergarten_orig_folder_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionPriceSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Настройка цен и выкупа',
                'verbose_name_plural': 'Глобальные настройки цен',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('kindergarten.region',),
        ),
    ]
