# Generated by Django 5.1.7 on 2025-03-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0020_regionpricesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindergarten',
            name='has_photobook',
            field=models.BooleanField(default=True, verbose_name='Наличие фотокниги'),
        ),
    ]
