# Generated by Django 5.1.2 on 2024-10-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0005_permission_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание права'),
        ),
    ]
