# Generated by Django 5.1.2 on 2024-10-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0006_permission_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='region',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Руководитель отдела продаж'), (2, 'Менеджер'), (3, 'Исполнительный директор')], default=2, verbose_name='Роль пользователя'),
        ),
        migrations.DeleteModel(
            name='ClientCard',
        ),
    ]
