# Generated by Django 5.1.3 on 2024-11-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0007_remove_employee_department_remove_employee_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Руководитель отдела продаж'), (2, 'Менеджер'), (3, 'Исполнительный директор'), (4, 'Старший менеджер')], default=2, verbose_name='Роль пользователя'),
        ),
    ]
