# Generated by Django 5.1.3 on 2024-11-07 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0008_alter_employee_employee_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'employee_role': 4}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roles.employee', verbose_name='Руководитель'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('manager', 'user'), name='unique_manager_assignment'),
        ),
    ]
