# Generated by Django 5.1.3 on 2024-11-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0009_employee_manager_employee_unique_manager_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_edit_task',
            field=models.BooleanField(default=False, verbose_name='Может редактировать задачу'),
        ),
    ]
