# Generated by Django 5.1.3 on 2024-11-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0010_employee_can_edit_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'РОП'), (2, 'Менеджер'), (3, 'Исполнительный директор'), (4, 'Старший менеджер')], default=2, verbose_name='Роль пользователя'),
        ),
    ]
