# Generated by Django 5.1.2 on 2024-10-28 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0007_remove_employee_department_remove_employee_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Изменен в')),
                ('client_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='client_cards.clientcard', verbose_name='Карточка клиента')),
                ('new_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_manager', to='roles.employee', verbose_name='Новый менеджер')),
                ('previous_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_managers', to='roles.employee', verbose_name='Прошлый менеджер')),
            ],
        ),
    ]
