# Generated by Django 5.0.6 on 2024-06-19 15:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kindergarten', '0002_alter_photoprice_photo_type'),
        ('parent', '0006_emailerrorlog_delete_sendemailerror'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена заказа')),
                ('status', models.CharField(choices=[('status1', 'Статус1'), ('status2', 'Статус2'), ('status3', 'Статус3')], default='Не задан', max_length=200, verbose_name='Статус заказа')),
                ('kindergarden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='kindergarten.kindergarten', verbose_name='Детский сад')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='parent.parent', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': ('Заказ',),
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
