# Generated by Django 5.0.6 on 2024-06-24 11:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kindergarten', '0002_alter_photoprice_photo_type'),
        ('parent', '0008_remove_parent_user_ptr_parent_id_parent_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('order_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена заказа')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Создан'), (2, 'Оплачен')], default=1, verbose_name='Статус заказа')),
                ('kindergarden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='kindergarten.kindergarten', verbose_name='Детский сад')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='parent.parent', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('photo_type', models.PositiveSmallIntegerField(choices=[(1, '10x15'), (2, '15x20'), (3, '20x30'), (4, 'Магнит'), (5, 'Календарь')], default=3, verbose_name='Тип фото')),
                ('is_digital', models.BooleanField(default=False, verbose_name='В электронном виде')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('photo', models.UUIDField(verbose_name='Фотография')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Часть заказа',
                'verbose_name_plural': 'Части заказа',
            },
        ),
    ]
