# Generated by Django 5.0.6 on 2024-07-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='photo_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '10x15'), (2, '15x20'), (3, '20x30'), (4, 'Магнит'), (5, 'Календарь'), (6, 'Фотокнига')], default=3, verbose_name='Тип фото'),
        ),
    ]
