# Generated by Django 5.0.6 on 2024-06-20 08:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_type', models.CharField(choices=[('10x15', '10x15'), ('15x20', '15x20'), ('20x30', '20x30'), ('magnet', 'Магнит'), ('calendar', 'Календарь')], default='10x15', max_length=200, verbose_name='Тип фото')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('photo', models.UUIDField(verbose_name='Фотография')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.order', verbose_name='Заказ')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
