# Generated by Django 5.0.6 on 2024-07-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderitem_photo_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='is_digital',
        ),
        migrations.AddField(
            model_name='order',
            name='is_digital',
            field=models.BooleanField(default=False, verbose_name='Электронные фотографии'),
        ),
    ]
