# Generated by Django 5.0.6 on 2024-06-20 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_options_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Часть заказа', 'verbose_name_plural': 'Части заказа'},
        ),
    ]
