# Generated by Django 5.0.6 on 2024-06-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_digital',
            field=models.BooleanField(default=False, verbose_name='В электронном виде'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('paid_for', 'Оплачен')], default='Не задан', max_length=200, verbose_name='Статус заказа'),
        ),
    ]
