# Generated by Django 5.0.6 on 2024-07-06 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderitem_photo_type'),
        ('order', '0003_remove_orderitem_is_digital_order_is_digital'),
    ]

    operations = [
    ]
