# Generated by Django 5.0.6 on 2024-06-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderitem_is_digital_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='photo_type',
            field=models.CharField(blank=True, choices=[('10x15', '10x15'), ('15x20', '15x20'), ('20x30', '20x30'), ('magnet', 'Магнит'), ('calendar', 'Календарь')], default='10x15', max_length=200, null=True, verbose_name='Тип фото'),
        ),
    ]
