# Generated by Django 5.0.6 on 2024-07-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_orderitem_is_digital_order_is_digital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Создан'), (2, 'Оплачен'), (3, 'Электронные фото готовы'), (4, 'Выполнен')], default=1, verbose_name='Статус заказа'),
        ),
    ]
