# Generated by Django 5.0.7 on 2024-07-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_photobook',
            field=models.BooleanField(default=False, verbose_name='Фотокнига'),
        ),
    ]
