# Generated by Django 5.0.7 on 2024-07-17 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_order_kindergarten_order_photo_line'),
        ('photo', '0003_photoline_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='photo_line',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='photo.photoline', verbose_name='Фотолиния'),
        ),
    ]
