# Generated by Django 5.0.8 on 2024-08-20 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_payment_id'),
        ('photo', '0009_alter_photoline_options_alter_phototheme_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='photo_line',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='photo.photoline', verbose_name='Пробник'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Создан'), (2, 'Оплачен'), (3, 'Электронные фото готовы'), (4, 'Выполнен'), (5, 'Ожидает оплаты'), (6, 'Платеж отклонен'), (7, 'Платеж возвращен')], default=1, verbose_name='Статус заказа'),
        ),
    ]
