# Generated by Django 5.0.8 on 2024-08-27 10:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_orderitem_price_alter_orderitem_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Оплата заказа',
                'verbose_name_plural': 'Оплата заказов',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.orderspayment', verbose_name='Оплата заказа'),
        ),
    ]
