# Generated by Django 5.1.1 on 2024-09-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_notificationfiscalization_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderspayment',
            name='is_closing_receipt_sent',
            field=models.BooleanField(default=False, verbose_name='Отправлен закрывающий чек'),
        ),
    ]
