# Generated by Django 5.1.1 on 2024-09-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_notificationfiscalization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_free_calendar',
            field=models.BooleanField(default=False, verbose_name='Бесплатный календарь'),
        ),
    ]
