# Generated by Django 5.1.1 on 2024-09-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_order_is_free_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='photo_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '10x15'), (2, '15x20'), (3, '20x30'), (4, 'Магнит'), (5, 'Календарь'), (6, 'Фотокнига'), (7, 'Календарь в подарок'), (0, 'Электронные фото')], default=3, verbose_name='Тип фото'),
        ),
    ]
