# Generated by Django 5.1.1 on 2024-09-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_orderspayment_is_closing_receipt_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationfiscalization',
            name='notification',
            field=models.JSONField(),
        ),
    ]
