# Generated by Django 5.1.3 on 2024-11-06 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_orderitem_photo_type'),
        ('photo', '0021_alter_photo_photo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='photo_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='photo.photoline', verbose_name='Пробник'),
        ),
    ]
