# Generated by Django 5.1.4 on 2024-12-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_order_photo_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_free_digital',
            field=models.BooleanField(default=False, verbose_name='Эл. фото в подарок'),
        ),
    ]
