# Generated by Django 5.1.6 on 2025-02-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_order_is_free_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Изначальная сумма заказа'),
        ),
    ]
