# Generated by Django 5.1.6 on 2025-03-05 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_order_original_price'),
        ('photo', '0034_alter_phototheme_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='photo_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='photo.photoline', verbose_name='Пробник'),
        ),
    ]
