# Generated by Django 5.1.6 on 2025-03-05 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_alter_cartphotoline_cart_and_more'),
        ('order', '0020_alter_order_photo_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_photo_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cart.cartphotoline', verbose_name='Пробник в корзине'),
        ),
    ]
