# Generated by Django 5.1.6 on 2025-03-06 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_cartphotoline_kindergarten_cartphotoline_user'),
        ('order', '0022_alter_order_cart_photo_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart_photo_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_orders', to='cart.cartphotoline', verbose_name='Пробник в корзине'),
        ),
    ]
