# Generated by Django 5.0.6 on 2024-06-24 15:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kindergarten', '0002_alter_photoprice_photo_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, null=True, unique=True, verbose_name='Код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('purpose', models.IntegerField(choices=[(1, 'Сброс пароля'), (2, 'Подтверждение email')], verbose_name='Цель')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='EmailErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение ошибки')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('confirm_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='parent.confirmcode', verbose_name='Код')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Родитель')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтверждение email')),
                ('kindergarten', models.ManyToManyField(related_name='parents', to='kindergarten.kindergarten', verbose_name='Детский сад')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Родитель',
                'verbose_name_plural': 'Родители',
            },
        ),
    ]
