# Generated by Django 5.0.6 on 2024-06-13 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Подтверждение email'),
        ),
        migrations.CreateModel(
            name='ConfirmCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.IntegerField(choices=[(1, 'Сброс пароля'), (2, 'Подтверждение email')])),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent.parent')),
            ],
        ),
    ]
