# Generated by Django 5.0.6 on 2024-06-14 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0002_parent_is_verified_confirmcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmcode',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='confirmcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='confirmcode',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent.parent', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='confirmcode',
            name='purpose',
            field=models.IntegerField(choices=[(1, 'Сброс пароля'), (2, 'Подтверждение email')], verbose_name='Цель'),
        ),
        migrations.CreateModel(
            name='SendEmailError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение ошибки')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('confirm_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parent.confirmcode', verbose_name='Код')),
            ],
        ),
    ]
