# Generated by Django 5.0.6 on 2024-06-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0003_alter_confirmcode_code_alter_confirmcode_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmcode',
            name='code',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Код'),
        ),
    ]
