# Generated by Django 5.0.6 on 2024-06-14 14:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0004_alter_confirmcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmcode',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Использован'),
        ),
        migrations.AddField(
            model_name='sendemailerror',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
    ]
