# Generated by Django 5.0.6 on 2024-06-17 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0005_confirmcode_is_used_sendemailerror_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение ошибки')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('confirm_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='parent.confirmcode', verbose_name='Код')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parent.parent', verbose_name='Родитель')),
            ],
        ),
        migrations.DeleteModel(
            name='SendEmailError',
        ),
    ]
