# Generated by Django 5.0.6 on 2024-06-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0007_remove_confirmcode_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailerrorlog',
            name='confirm_code',
        ),
        migrations.RemoveField(
            model_name='emailerrorlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='kindergarten',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='user',
        ),
        migrations.DeleteModel(
            name='ConfirmCode',
        ),
        migrations.DeleteModel(
            name='EmailErrorLog',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
