# Generated by Django 5.0.6 on 2024-06-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_role_alter_user_second_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Родитель'), (2, 'Заведующий')], default=1, verbose_name='Роль'),
        ),
    ]
