# Generated by Django 5.0.6 on 2024-06-25 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_options_user_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, null=True, unique=True, verbose_name='Код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('purpose', models.PositiveSmallIntegerField(choices=[(1, 'Сброс пароля'), (2, 'Подтверждение email')], verbose_name='Цель')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Код подтверждения',
                'verbose_name_plural': 'Коды подтверждения',
            },
        ),
        migrations.CreateModel(
            name='EmailErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение об ошибке')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('confirm_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.confirmcode', verbose_name='Код')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
