# Generated by Django 5.0.6 on 2024-07-03 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_staffuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerBonus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('start_period_date', models.DateTimeField(verbose_name='Дата начала периода')),
                ('end_period_date', models.DateTimeField(verbose_name='Дата окончания периода')),
                ('bonus_size', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Размер бонуса %')),
                ('total_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая сумма бонуса')),
                ('paid_for', models.BooleanField(default=False, verbose_name='Выплачен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_bonuses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бонус заведующей с продаж',
                'verbose_name_plural': 'Бонусы заведующих с продаж',
            },
        ),
    ]
