# Generated by Django 5.0.6 on 2024-07-04 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_staffuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailerrorlog',
            options={'verbose_name': 'Ошибка отправки email', 'verbose_name_plural': 'Ошибки отправки email'},
        ),
    ]
