# Generated by Django 5.0.6 on 2024-07-06 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_emailerrorlog_options'),
        ('user', '0009_managerbonus'),
    ]

    operations = [
    ]
