# Generated by Django 5.0.7 on 2024-07-19 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailerrorlog',
            name='confirm_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.confirmcode', verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='emailerrorlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
