# Generated by Django 5.0.7 on 2024-07-27 14:26

import apps.user.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=56, validators=[django.core.validators.MinLengthValidator(2), apps.user.validators.validate_cyrillic], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=56, validators=[django.core.validators.MinLengthValidator(2), apps.user.validators.validate_cyrillic], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(blank=True, max_length=56, validators=[django.core.validators.MinLengthValidator(2), apps.user.validators.validate_cyrillic], verbose_name='Отчество'),
        ),
    ]
