# Generated by Django 5.0.7 on 2024-07-28 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=56, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message='Можно вводить только кириллические символы.', regex='^[А-Яа-яЁё]+$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=56, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message='Можно вводить только кириллические символы.', regex='^[А-Яа-яЁё]+$')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(blank=True, max_length=56, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message='Можно вводить только кириллические символы.', regex='^[А-Яа-яЁё]+$')], verbose_name='Отчество'),
        ),
    ]
