# Generated by Django 5.0.2 on 2024-08-21 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='promocode',
        ),
    ]
