# Generated by Django 5.1.1 on 2024-09-24 14:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0012_alter_photoprice_photo_type'),
        ('photo', '0011_alter_coefficient_photo_type'),
        ('user', '0016_remove_user_promocode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerbonus',
            name='end_period_date',
        ),
        migrations.RemoveField(
            model_name='managerbonus',
            name='start_period_date',
        ),
        migrations.AddField(
            model_name='managerbonus',
            name='photo_theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_bonuses', to='photo.phototheme', verbose_name='Фототема'),
        ),
        migrations.AddField(
            model_name='user',
            name='managed_kindergarten',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to='kindergarten.kindergarten', verbose_name='Детский сад (заведующий)'),
        ),
        migrations.AlterField(
            model_name='managerbonus',
            name='bonus_size',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Размер бонуса %'),
        ),
    ]
