# Generated by Django 5.1.1 on 2024-10-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_remove_managerbonus_end_period_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Родитель'), (2, 'Заведующий'), (3, 'Сотрудник компании')], default=1, verbose_name='Роль'),
        ),
    ]
