# Generated by Django 5.1.2 on 2024-10-29 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0017_alter_phototheme_options_phototheme_season_and_more'),
        ('user', '0019_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerbonus',
            name='photo_theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_bonuses', to='photo.phototheme', verbose_name='Фотосессия'),
        ),
    ]
