# Generated by Django 5.1.3 on 2024-11-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0015_ransom_average_bill'),
        ('user', '0021_user_manager_discount_user_manager_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='un_hashed_password',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Пароль заведующей'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kindergarten',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='kindergarten.kindergarten', verbose_name='Детский сад'),
        ),
    ]
