# Generated by Django 5.1.5 on 2025-01-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_user_second_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='manager_discount',
            field=models.DecimalField(decimal_places=2, default=3000, max_digits=3, verbose_name='Скидка заведующей'),
        ),
    ]
