# Generated by Django 5.1.5 on 2025-01-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_user_manager_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manager_discount_balance',
            field=models.PositiveIntegerField(default=3000, verbose_name='Баланс заведующей на бесплатный заказ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='manager_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Скидка заведующей'),
        ),
    ]
