# Generated by Django 5.1.5 on 2025-01-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_user_manager_discount_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='manager_discount_balance',
            field=models.PositiveIntegerField(blank=True, default=3000, null=True, verbose_name='Баланс заведующей на бесплатный заказ'),
        ),
    ]
