# Generated by Django 5.1.7 on 2025-03-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_user_manager_discount_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manager_discount_balance_empty',
            field=models.BooleanField(default=False, verbose_name='Доступность бонуса заведующей'),
        ),
    ]
