# Generated by Django 5.1.7 on 2025-03-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_user_manager_discount_balance_empty'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manager_discount_intermediate_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Промежуточная таблица с бонусным балансом'),
        ),
    ]
