# Generated by Django 5.1.7 on 2025-03-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_user_manager_discount_intermediate_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='manager_discount_intermediate_balance',
            field=models.PositiveIntegerField(default=3000, verbose_name='Промежуточная таблица с бонусным балансом'),
        ),
    ]
