# Generated by Django 5.1.7 on 2025-03-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_user_manager_discount_intermediate_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='use_manager_coupon',
            field=models.BooleanField(default=False, verbose_name='Использовал промокод заведующей'),
        ),
    ]
