name: Deploy to Server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH with Password
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: 77.232.37.60
          username: root
          password: wLuUMMh53kt728Z3
          port: 22
          script: |
            cd /home/photo_portal
            git pull origin main
            docker-compose down
            docker-compose up -d
